# Generated by Django 5.2.14 on 2026-05-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_analysisrun_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
