# Generated by Django 5.2.14 on 2026-05-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_repository_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='auth_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='auth_token_warning',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
