# Generated by Django 5.2.14 on 2026-05-31 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0009_add_user_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='scan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RepoOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('pick_number', models.IntegerField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spotlights', to='repositories.repository')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('repo', 'week_start')},
            },
        ),
    ]
