# Generated by Django 5.2.14 on 2026-06-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0013_security_fixes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analysisrun',
            name='analysisrun_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='analysisrun',
            name='analysisrun_triggered_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='repository',
            name='repository_is_watched_idx',
        ),
        migrations.RemoveIndex(
            model_name='repository',
            name='repository_is_private_idx',
        ),
    ]
