# Generated by Django 5.2.14 on 2026-06-01 15:09

import django.db.models.deletion
from uuid_extensions import uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0014_remove_analysisrun_analysisrun_status_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid7, editable=False, primary_key=True, serialize=False)),
                ('delivery_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('repo_url', models.CharField(blank=True, default='', max_length=500)),
                ('triggered_reanalysis', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_deliveries', to='repositories.analysisrun')),
            ],
            options={
                'verbose_name_plural': 'webhook deliveries',
                'ordering': ['-received_at'],
            },
        ),
    ]
