# Generated by Django 5.2.14 on 2026-06-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0015_featureflag_webhookdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='progress_step',
            field=models.CharField(blank=True, choices=[('', ''), ('cloning', 'Cloning repository'), ('parsing', 'Parsing imports & structure'), ('heuristics', 'Computing heuristics'), ('metadata', 'Fetching GitHub metadata'), ('finalizing', 'Finalizing results')], default='', max_length=20),
        ),
    ]
