# Generated by Django 5.2.14 on 2026-06-03 13:48

import uuid_extensions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0016_add_progress_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.UUIDField(default=uuid_extensions.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('edges', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('repos', models.ManyToManyField(blank=True, related_name='constellations', to='repositories.repository')),
            ],
        ),
    ]
