# Generated by Django 5.2.14 on 2026-06-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0017_constellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='commit_sha',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
