# Generated by Django 5.2.14 on 2026-06-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0018_analysisrun_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='cached_branch_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
