# Generated by Django 5.2.14 on 2026-06-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0021_fix_default_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='tools_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
